# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "tpm_tis" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-99617911-0cdb-4012-b833-9b23bc548194";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-99617911-0cdb-4012-b833-9b23bc548194".device = "/dev/disk/by-uuid/99617911-0cdb-4012-b833-9b23bc548194";
  boot.initrd.luks.devices."luks-99617911-0cdb-4012-b833-9b23bc548194".crypttabExtraOpts = [ "tpm2-device=auto" ];

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/79C6-184F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
